annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.6-c10d675dd52cf26f87e2c3171b61ce0751203e04.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.6-c10d675dd52cf26f87e2c3171b61ce0751203e04.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.6-c10d675dd52cf26f87e2c3171b61ce0751203e04.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-agent-0.1.6-c10d675dd52cf26f87e2c3171b61ce0751203e04.tgz
dateCreated: '2022-12-19T13:50:24.009973'
digest: 4921fdf5b5106cc68ffc3ae5598d75067064deac9874b0088222b25920513756
home: https://github.com/giantswarm/prometheus-agent-app
restrictions:
  clusterSingleton: true
