annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.6-cc729e5d778c4caf6eca25cbb0d5990b37c9fa71.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.6-cc729e5d778c4caf6eca25cbb0d5990b37c9fa71.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.6-cc729e5d778c4caf6eca25cbb0d5990b37c9fa71.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-agent-0.1.6-cc729e5d778c4caf6eca25cbb0d5990b37c9fa71.tgz
dateCreated: '2022-12-06T17:31:04.376211'
digest: ab853f8410debdd5e2b8f49f850f822936de8765a2e35eddfdb3bb7906946e47
home: https://github.com/giantswarm/prometheus-agent-app
restrictions:
  clusterSingleton: true
