annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-ec5677f62a5edb3e601989dd0804cc3a76866eb0.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-ec5677f62a5edb3e601989dd0804cc3a76866eb0.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-ec5677f62a5edb3e601989dd0804cc3a76866eb0.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-agent-0.1.7-ec5677f62a5edb3e601989dd0804cc3a76866eb0.tgz
dateCreated: '2023-01-23T13:04:32.097342'
digest: f2e8ebdb57892e3b00e776cbcc5e27f42126452d5716531c6531849faaa2f689
home: https://github.com/giantswarm/prometheus-agent-app
restrictions:
  clusterSingleton: true
