annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-fb88a6367bc50c316d928e291bdf413e356b95c4.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-fb88a6367bc50c316d928e291bdf413e356b95c4.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-fb88a6367bc50c316d928e291bdf413e356b95c4.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-agent-0.1.7-fb88a6367bc50c316d928e291bdf413e356b95c4.tgz
dateCreated: '2023-01-26T19:46:27.954575'
digest: 71dec89852507253bb881ebf8df1604bdd7ff41c35574715ee494d4074812190
home: https://github.com/giantswarm/prometheus-agent-app
restrictions:
  clusterSingleton: true
