annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-ee66be4927c3dbdeefc5322ce51cac28dca30f88.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-ee66be4927c3dbdeefc5322ce51cac28dca30f88.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-ee66be4927c3dbdeefc5322ce51cac28dca30f88.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-agent-0.1.7-ee66be4927c3dbdeefc5322ce51cac28dca30f88.tgz
dateCreated: '2023-01-24T13:54:53.440327'
digest: c9ac5068bde93333b22305530b008d6067c6e0cf9c9f1c623e6e16b18cfd97c2
home: https://github.com/giantswarm/prometheus-agent-app
restrictions:
  clusterSingleton: true
