annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-29415cb86e25fbdabbc4812cf78b312685eda543.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-29415cb86e25fbdabbc4812cf78b312685eda543.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-29415cb86e25fbdabbc4812cf78b312685eda543.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-agent-0.1.7-29415cb86e25fbdabbc4812cf78b312685eda543.tgz
dateCreated: '2023-01-27T20:27:56.601589'
digest: 0cc6d841ee4b635b693aa34c1e00f4f934ca2bd30eebf607abccc2744ecd47a9
home: https://github.com/giantswarm/prometheus-agent-app
restrictions:
  clusterSingleton: true
