annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-13975307a51609bc5943cf1b745e72042bd5c1bb.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-13975307a51609bc5943cf1b745e72042bd5c1bb.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-13975307a51609bc5943cf1b745e72042bd5c1bb.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-agent-0.1.7-13975307a51609bc5943cf1b745e72042bd5c1bb.tgz
dateCreated: '2023-01-20T17:54:23.490729'
digest: 293360c49e890227e62c9555fd445e40778e6af0e5dee4f9fb1f7ee72ef5d662
home: https://github.com/giantswarm/prometheus-agent-app
restrictions:
  clusterSingleton: true
