annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-5366c19cbd0bec757c30b1ef8c8eb967469d097f.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-5366c19cbd0bec757c30b1ef8c8eb967469d097f.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-5366c19cbd0bec757c30b1ef8c8eb967469d097f.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-agent-0.1.7-5366c19cbd0bec757c30b1ef8c8eb967469d097f.tgz
dateCreated: '2023-02-06T08:12:23.630951'
digest: 70077c5dafb4b05267326eb34cfda49f15f874d211b6fe2c357bd1853921696d
home: https://github.com/giantswarm/prometheus-agent-app
restrictions:
  clusterSingleton: true
