annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.5-e585b036f1d1d99f5c861b68766e525234bd809e.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.5-e585b036f1d1d99f5c861b68766e525234bd809e.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.5-e585b036f1d1d99f5c861b68766e525234bd809e.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-agent-0.1.5-e585b036f1d1d99f5c861b68766e525234bd809e.tgz
dateCreated: '2022-12-06T10:31:33.120496'
digest: 94fb9e5f23c0efcac74b99de68706d6c3ff21fe32eac50e55d409c358ee1f657
home: https://github.com/giantswarm/prometheus-agent-app
restrictions:
  clusterSingleton: true
