annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-93b931909d529763d5f76d7b0cae6b3d1d9b7768.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-93b931909d529763d5f76d7b0cae6b3d1d9b7768.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-playground-test-catalog/prometheus-agent-0.1.7-93b931909d529763d5f76d7b0cae6b3d1d9b7768.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-agent-0.1.7-93b931909d529763d5f76d7b0cae6b3d1d9b7768.tgz
dateCreated: '2023-01-24T17:41:45.985431'
digest: 5ef3d5386634124d9b131f3532d86d8d21875d516e79f1f2ad6a830d5c5d5393
home: https://github.com/giantswarm/prometheus-agent-app
restrictions:
  clusterSingleton: true
