name: GiantSwarm Playground Test Catalog Cleanup
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  cleanup:
    uses: giantswarm/app-catalog-cleanup-tool/.github/workflows/cleanup.yaml@main
    with:
      delete-before: "1 month"
      dry-run: false
